---
- name: add group
  become: true
  group:
    name: nginx-exp
    state: present

- name: add user
  become: true
  user:
    name: nginx-exp
    state: present
    groups: nginx-exp

- name: Download
  become: true
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /home

- name: unarchive nginx-prometheus-exporter
  become: true
  unarchive:
    src: /home/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true

- template:
    src: nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service
    owner: nginx
    group: nginx
    mode: '0644'
