---
- name: add group
  become: true
  group:
    name: nginx-exp
    state: present

- name: add user
  become: true
  user:
    name: nginx-exp
    state: present
    groups: nginx-exp

- name: Download 
  become: true
  get url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: /home

